server:
  port: 9090
database:
  test: testsmsproject
  name: smsproject
  user: postgres
  password: 1236
  host: localhost
  port: 54321
  ssl: disable
  timezone: Asia/Tehran
pgadmin:
  mail: admin@example.com
  pw: admin
jwt:
  token:
    expire:
      hours: 1
    secret:
      key: S2jd2el2d92lSAm2wso272Als
encryption:
  secret:
    key: Wdn29o32sxQAS2qsQmjs23dx8s
payment:
  redirect:
    url: http://localhost:9090/payments/callback
  gateways:
    saderat:
      terminal:
        id: 134754392
      urls:
        token: https://sandbox.banktest.ir/saderat/sepehr.shaparak.ir/V1/PeymentApi/GetToken
        payment: https://sandbox.banktest.ir/saderat/sepehr.shaparak.ir/Pay
        verify: https://sandbox.banktest.ir/saderat/sepehr.shaparak.ir/V1/PeymentApi/Advice
app:
  reserved: empty
  debugMode: true
  imageLogo: img/go-dragon.png
  ticketFileName: pdf/ticket.pdf
