version: "3.9"

services:
  sms-postgres:
    image: postgres:15.3-alpine
    hostname: ${DATABASE_HOST}
    container_name: sms-postgres
    command: -p ${DATABASE_PORT} # Change the default port
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "${DATABASE_PORT}"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    restart: always
    volumes:
      - airplane-postgres:/var/lib/postgresql/data

  sms-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sms-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always

  sms-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "./wait-for-it.sh ${DATABASE_HOST}:${DATABASE_PORT} -- ./main"
    container_name: sms-backend
    depends_on:
      - sms-postgres
    hostname: backend
    working_dir: /root/
    restart: always
    env_file:
      - ".env"
    ports:
      - "${EXPOSE_PORT}:${EXPOSE_PORT}"

volumes:
  airplane-postgres: